os: linux
dist: xenial
language: php

php: 7.2

install:
  - composer install

before_script:
  - cp .env.example .env
  - php artisan k:g
  - php artisan oidc:discover

script:
  - php vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache/files
    - vendor
