os: linux
dist: xenial
language: php

php: 7.4

install:
  - composer install

before_script:
  - cp .env.example .env
  - php artisan key:generate
  - php artisan oidc:discover:line

script:
  - php vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache/files
    - vendor
